# Generated by Django 4.2.3 on 2023-07-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img',
            field=models.CharField(default='default.jpg', max_length=250),
        ),
    ]
